import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import SignInButton from "./SignInButton";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import SignOutButton from "./SignOutButton";
import { cookies } from "next/headers";
import PageThema from "./PageThema";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions) // 로그인한 유저 정보 출력

  const pageThema = cookies().get('pageThema')
  console.log(pageThema)

  return (
    <html lang="en">
      <body className={pageThema != undefined && pageThema.value == 'dark' ? "dark-mode" : ''}>
        <div className="navbar">
          <div className="nav-inner">
            <Link href="/" className="logo">Forum</Link>
            <Link href="/list">게시판</Link>
            <Link href="/write">글쓰기</Link>
          </div>
          <div className="nav-inner">
            {
              session ?
                <>
                  <h5>{session.user.name}</h5>
                  <SignOutButton />
                </> :
                <>
                  <SignInButton />
                  <Link href="/register">회원가입</Link>
                </>
            }
            <PageThema nowPageThema={pageThema} />
          </div>
        </div>
        {children}</body>
    </html>
  );
}
